# Generated by Django 5.2.8 on 2025-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
