# Generated by Django 5.2.8 on 2025-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0002_talk_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='talk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date last updated'),
        ),
    ]
