# Generated by Django 5.2.8 on 2025-11-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0003_remove_talk_updated_date_talk_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programdesigner.event')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programdesigner.program')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programdesigner.talk')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('talk', 'program')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='talks',
            field=models.ManyToManyField(through='programdesigner.ProgramTalk', to='programdesigner.talk'),
        ),
    ]
