# Generated by Django 5.2.8 on 2025-11-21 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0004_event_alter_speaker_title_program_programtalk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtalk',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programtalk',
            name='start_time',
            field=models.TimeField(default=datetime.time(11, 0)),
            preserve_default=False,
        ),
    ]
