# Generated by Django 5.2.8 on 2025-11-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0005_programtalk_end_time_programtalk_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtalk',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='programtalk',
            name='order',
        ),
    ]
