# Generated by Django 5.2.8 on 2025-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0006_alter_programtalk_options_remove_programtalk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
