# Generated by Django 5.2.8 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdesigner', '0008_alter_event_name_alter_speaker_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
